#el archivo application contiene el puerto de la aplicacion y la coneccion con el eureka server

#Puerto donde se desplegara la aplicacion
server:
  port: 8686
  

#Configurcion de la coneccion con el eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      instance:
        hostname: localhost
        nonSecurePort: 8686
        